-- AlterTable
ALTER TABLE "warranties" ADD COLUMN     "warranty_note" TEXT,
ADD COLUMN     "admin_note" TEXT,
ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
